# Generated by Django 3.1.1 on 2020-10-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=200, verbose_name='Порода')),
                ('breed_description', models.TextField(verbose_name='Характеристика породы')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.animal', verbose_name='Вид')),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.SmallIntegerField(null=True, verbose_name='Примерный возраст')),
                ('story', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата поступления')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.animal', verbose_name='Вид')),
                ('breed', models.ManyToManyField(to='pets.Breed', verbose_name='Порода')),
            ],
        ),
    ]
