# Generated by Django 3.1.1 on 2020-10-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201002_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_description',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристика породы'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Примерный возраст'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='gender',
            field=models.BooleanField(blank=True, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
