# Generated by Django 3.1.1 on 2020-10-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201002_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='animal_type',
            new_name='animal_type_ref',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='animal_type',
            new_name='animal_type_ref',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='breed_ref',
        ),
    ]
