# Generated by Django 3.1.1 on 2020-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20201002_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(max_length=20, verbose_name='Вид'),
        ),
    ]
