# Generated by Django 3.1.1 on 2020-10-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20201002_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Примерный возраст'),
        ),
    ]
