# Generated by Django 3.1.1 on 2020-10-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20201003_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='breed_ref',
        ),
    ]
