# Generated by Django 3.1.1 on 2020-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20201003_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(True, 'Мальчик'), (False, 'Девочка')], default=True, null=True, verbose_name='Пол'),
        ),
    ]
